spring:
  datasource:
    url: jdbc:h2:mem:spring-boot-dev-db
    username: dev-admin
    password: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks