server:
  port: 8082

spring:
  profiles.active: local

  datasource:
    url: jdbc:h2:file:./db/default/spring-boot-default-db
    username: default-admin
    password: default
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml

debug: true