spring:
  datasource:
    url: jdbc:h2:mem:spring-boot-stg-db
    username: stg-admin
    password: stg

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

  jpa:
    show-sql: false

  h2:
    console:
      enabled: false

debug: false