spring:
  datasource:
    url: jdbc:h2:file:./db/prod/spring-boot-prod-db
    username: prod-admin
    password: prod

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

  jpa:
    show-sql: false

  h2:
    console:
      enabled: false

debug: false